version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    networks:
      - mynetwork
    deploy:
      replicas: 3
      mode: replicated

  nginx:
    image: nginx:1.22.1
    build:
      context: .
      dockerfile: nginx-build
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
